// Mocks generated by Mockito 5.4.4 from annotations
// in tracking_stocks/test/features/presentaton/bloc/portfolio_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_stocks/features/portfolio/domain/model/portfolio.dart'
    as _i4;
import 'package:tracking_stocks/features/portfolio/domain/use_case/observe_portfolio_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ObservePortfolioUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObservePortfolioUseCase extends _i1.Mock
    implements _i2.ObservePortfolioUseCase {
  @override
  _i3.Stream<_i4.Portfolio> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i3.Stream<_i4.Portfolio>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.Portfolio>.empty(),
      ) as _i3.Stream<_i4.Portfolio>);
}
